# 운영 환경 설정
spring:
  application:
    name: fitness-coaching-api

  # PostgreSQL 데이터베이스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Spring Security 인증 설정
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # 운영 환경에서는 update 사용
    show-sql: false  # 운영 환경에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# CORS 설정 (운영 환경 - 환경 변수로 설정)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-frontend-domain.com}

# Swagger 설정 (운영 환경에서는 비활성화)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.fitness.coaching: INFO