spring:
  application:
    name: fitness-coaching-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080

logging:
    level:
      root: INFO
      com.fitness.coaching: DEBUG